helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/tucaken-app
    forcestring: true
  - name: image.tag
    value: eca4abd2c78b4b45753d28ab7454354c0bb38e57-r1
    forcestring: true
