helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/tucaken-app
    forcestring: true
  - name: image.tag
    value: a08aa7b2ece52441721c364c212bc61efedd14ad-r1
    forcestring: true
