helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/tucaken-app
    forcestring: true
  - name: image.tag
    value: aee03e9c0bb08820986fc85618b32e766236b9ae-r1
    forcestring: true
