helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/public-api
    forcestring: true
  - name: image.tag
    value: bb751f6d1f503b893c6c2a5afb5eca5c5cf9109e-r1
    forcestring: true
