helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/public-api
    forcestring: true
  - name: image.tag
    value: a7d799f0b5f5b3aa55ad26798e2c7c6f5e6af2bd-r1
    forcestring: true
