helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/public-api
    forcestring: true
  - name: image.tag
    value: d2ea5d89ffb40fd74170286804b60b96e7c6ed38-r1
    forcestring: true
