helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/platform-job-watcher
    forcestring: true
  - name: image.tag
    value: 1252cad42657e6a27efd21c740a056a8ccc4e7e9-r1
    forcestring: true
