helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/platform-job-watcher
    forcestring: true
  - name: image.tag
    value: 195cbf0f074af6735c24d0eb8149a071e4199725-r1
    forcestring: true
