helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/platform-job-watcher
    forcestring: true
  - name: image.tag
    value: 69475c977185a63c40d060cdb26f9c1319de5faf-r1
    forcestring: true
