helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/platform-job-watcher
    forcestring: true
  - name: image.tag
    value: f731060c127d44bf28dacb812500ef12680ef480-r1
    forcestring: true
