helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/admin-api
    forcestring: true
  - name: image.tag
    value: ce134695a8ea2590e785d1c2210d180b058e3139-r1
    forcestring: true
