helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/admin-api
    forcestring: true
  - name: image.tag
    value: d82414205e5d952f0c50094a3b874134ef0b5b10-r1
    forcestring: true
