helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/ontology-importer
    forcestring: true
  - name: image.tag
    value: 0d3a820e634bf1221310dbd361fb2aa511dc42e1-r1
    forcestring: true
