helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/ontology-importer
    forcestring: true
  - name: image.tag
    value: cc9e1ff5cb4ee7e5629b58359ee7a0eaa0025031-r1
    forcestring: true
