helm:
  parameters:
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/ontology-importer
    forcestring: true
  - name: image.tag
    value: 679f48836bca60399f774d65c52e43733f10a4f7-r1
    forcestring: true
