{{- if .Values.grafana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.fullLabels" "grafana" | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/group.name: public
    alb.ingress.kubernetes.io/group.order: "200"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /grafana/api/health
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.adminAccess.hostname }}
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: {{ .Values.grafana.service.port }}
{{- end }}
