apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  labels: {{- include "monitoring.fullLabels" "grafana" | nindent 4 }}
  {{- with .Values.grafana.serviceAccount.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . | quote }}
  {{- end }}
automountServiceAccountToken: false
