{{- if .Values.alertmanager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace }}
  labels: {{- include "monitoring.fullLabels" "alertmanager" | nindent 4 }}
spec:
  replicas: {{ .Values.alertmanager.replicas }}
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      {{- include "monitoring.selectorLabels" "alertmanager" | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/alertmanager/configmap.yaml") . | sha256sum }}
      labels: {{- include "monitoring.fullLabels" "alertmanager" | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 65534
        runAsNonRoot: true
        fsGroup: 65534
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: alertmanager
          image: {{ .Values.alertmanager.image }}
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--storage.path=/alertmanager"
            - "--data.retention={{ .Values.alertmanager.retention }}"
            - "--web.listen-address=:{{ .Values.alertmanager.service.port }}"
            - "--web.external-url={{ .Values.alertmanager.externalUrl }}"
            - "--web.route-prefix=/"
          ports:
            - containerPort: {{ .Values.alertmanager.service.port }}
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            - name: data
              mountPath: /alertmanager
          resources: {{- toYaml .Values.alertmanager.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /-/ready
              port: {{ .Values.alertmanager.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: {{ .Values.alertmanager.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: config
          configMap:
            name: alertmanager-config
        - name: data
          persistentVolumeClaim:
            claimName: alertmanager-data
{{- end }}
