# @format
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-api-job-creator
  namespace: {{ .Values.namespace }}
  labels:
    app: job-strategist
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-api-job-creator
  namespace: {{ .Values.namespace }}
  labels:
    app: job-strategist
subjects:
  - kind: ServiceAccount
    name: {{ .Values.adminApi.serviceAccountName }}
    namespace: {{ .Values.adminApi.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-api-job-creator
