apiVersion: v1
kind: ResourceQuota
metadata:
  name: tucaken-app-quota
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tucaken-app.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.resourceQuota.hard | nindent 4 }}
